version: '3'
services:
  dev-db:
    image: postgres:16.4
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=spatial
      - POSTGRES_PASSWORD=spatial
      - POSTGRES_DB=spatial-server
    volumes:
      - ./data/dev-postgres:/var/lib/postgresql/data
  test-db:
    image: postgres:16.4
    ports:
      - "55433:5432"
    environment:
      - POSTGRES_USER=spatial
      - POSTGRES_PASSWORD=spatial
      - POSTGRES_DB=spatial-server
    volumes:
      - ./data/test-postgres:/var/lib/postgresql/data
